# Standard PISO: one momentum predictor and three pressure correctors.
maxIterations 1
nCorrectors 8
nonOrthogonalCorrections 1
velocityRelaxation 1.0
continuityTolerance 1.0e-8
velocityTolerance 1.0e-6
momentumTolerance 1.0e-5
pressureCorrectionTolerance 1.0e-6
turbulenceRelaxation 1.0
turbulenceTolerance 0.05
turbulenceMaxIterations 1
turbulenceCoupling segregated
initializePotentialFlow 0

equation.momentum.kspType bcgs
equation.momentum.pcType hypre
equation.momentum.absoluteTolerance 1.0e-12
equation.momentum.relativeTolerance 1.0e-9
equation.momentum.maxIterations 1000

equation.pressureCorrection.kspType cg
equation.pressureCorrection.pcType hypre
equation.pressureCorrection.warmStart true
equation.pressureCorrection.absoluteTolerance 1.0e-14
equation.pressureCorrection.relativeTolerance 1.0e-9
equation.pressureCorrection.maxIterations 2400

equation.kTransport.kspType bcgs
equation.kTransport.pcType hypre
equation.kTransport.absoluteTolerance 1.0e-18
equation.kTransport.relativeTolerance 1.0e-10
equation.kTransport.maxIterations 1000

equation.omegaTransport.kspType bcgs
equation.omegaTransport.pcType hypre
equation.omegaTransport.absoluteTolerance 1.0e-18
equation.omegaTransport.relativeTolerance 1.0e-10
equation.omegaTransport.maxIterations 1000
